# Generated by Django 6.0.2 on 2026-02-14 21:54

import django.db.models.deletion
import login.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('allergies', models.TextField(blank=True)),
                ('past_surgeries', models.TextField(blank=True)),
                ('diabetes', models.BooleanField(default=False)),
                ('hypertension', models.BooleanField(default=False)),
                ('heart_disease', models.BooleanField(default=False)),
                ('asthma', models.BooleanField(default=False)),
                ('chronic_kidney_disease', models.BooleanField(default=False)),
                ('previous_stroke', models.BooleanField(default=False)),
                ('smoker', models.BooleanField(default=False)),
                ('obese', models.BooleanField(default=False)),
                ('previous_heart_attack', models.BooleanField(default=False)),
                ('previous_hospitalization', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Emergency', 'Emergency'), ('General_Medicine', 'General Medicine'), ('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Pulmonology', 'Pulmonology'), ('Gastroenterology', 'Gastroenterology'), ('Orthopedics', 'Orthopedics'), ('Pediatrics', 'Pediatrics'), ('Nephrology', 'Nephrology'), ('Endocrinology', 'Endocrinology')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_emergencies', to=settings.AUTH_USER_MODEL)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_emergencies', to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_request', to='login.patient')),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(default=login.models.generate_employee_id, max_length=20, unique=True)),
                ('department', models.CharField(choices=[('Emergency', 'Emergency'), ('General_Medicine', 'General Medicine'), ('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Pulmonology', 'Pulmonology'), ('Gastroenterology', 'Gastroenterology'), ('Orthopedics', 'Orthopedics'), ('Pediatrics', 'Pediatrics'), ('Nephrology', 'Nephrology'), ('Endocrinology', 'Endocrinology')], max_length=50)),
                ('language', models.CharField(choices=[('auto', 'Auto-detect'), ('ta', 'Tamil'), ('hi', 'Hindi'), ('te', 'Telugu'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('mr', 'Marathi'), ('bn', 'Bengali'), ('gu', 'Gujarati'), ('ur', 'Urdu'), ('pa', 'Punjabi'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ko', 'Korean')], default='auto', max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TriageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic_bp', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('oxygen', models.IntegerField()),
                ('chest_pain', models.BooleanField(default=False)),
                ('severe_breathlessness', models.BooleanField(default=False)),
                ('sudden_confusion', models.BooleanField(default=False)),
                ('stroke_symptoms', models.BooleanField(default=False)),
                ('seizure', models.BooleanField(default=False)),
                ('severe_trauma', models.BooleanField(default=False)),
                ('uncontrolled_bleeding', models.BooleanField(default=False)),
                ('loss_of_consciousness', models.BooleanField(default=False)),
                ('severe_allergic_reaction', models.BooleanField(default=False)),
                ('persistent_fever', models.BooleanField(default=False)),
                ('vomiting', models.BooleanField(default=False)),
                ('moderate_abdominal_pain', models.BooleanField(default=False)),
                ('persistent_cough', models.BooleanField(default=False)),
                ('moderate_breathlessness', models.BooleanField(default=False)),
                ('severe_headache', models.BooleanField(default=False)),
                ('dizziness', models.BooleanField(default=False)),
                ('dehydration', models.BooleanField(default=False)),
                ('palpitations', models.BooleanField(default=False)),
                ('migraine', models.BooleanField(default=False)),
                ('mild_headache', models.BooleanField(default=False)),
                ('sore_throat', models.BooleanField(default=False)),
                ('runny_nose', models.BooleanField(default=False)),
                ('mild_cough', models.BooleanField(default=False)),
                ('fatigue', models.BooleanField(default=False)),
                ('body_ache', models.BooleanField(default=False)),
                ('mild_abdominal_pain', models.BooleanField(default=False)),
                ('skin_rash', models.BooleanField(default=False)),
                ('mild_back_pain', models.BooleanField(default=False)),
                ('mild_joint_pain', models.BooleanField(default=False)),
                ('predicted_risk', models.CharField(blank=True, max_length=10, null=True)),
                ('recommended_department', models.CharField(blank=True, choices=[('Emergency', 'Emergency'), ('General_Medicine', 'General Medicine'), ('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Pulmonology', 'Pulmonology'), ('Gastroenterology', 'Gastroenterology'), ('Orthopedics', 'Orthopedics'), ('Pediatrics', 'Pediatrics'), ('Nephrology', 'Nephrology'), ('Endocrinology', 'Endocrinology')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_requests', to=settings.AUTH_USER_MODEL)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_requests', to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triage_request', to='login.patient')),
            ],
        ),
    ]
