# Generated by Django 6.0.2 on 2026-02-14 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nurse',
            new_name='StaffProfile',
        ),
        migrations.AlterField(
            model_name='triagerequest',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='triagerequest',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
